export const productsList = [
  {
    id: 1,
    name: 'Wireless Mouse',
    min_quantity: 10,
    category: 'Electronics',
    current_quantity: 45,
    price: 29.99,
  },
  {
    id: 2,
    name: 'Mechanical Keyboard',
    min_quantity: 5,
    category: 'Electronics',
    current_quantity: 3,
    price: 89.99,
  },
  {
    id: 3,
    name: 'USB-C Cable',
    min_quantity: 20,
    category: 'Accessories',
    current_quantity: 15,
    price: 12.99,
  },
  {
    id: 4,
    name: 'Laptop Stand',
    min_quantity: 8,
    category: 'Furniture',
    current_quantity: 22,
    price: 45.99,
  },
];

export const recentEntriesList = [
  {
    id: 1,
    product: 'Wireless Mouse',
    quantity: 20,
    price: 25.0,
    added_by: 'John Doe',
    created_at: '2025-10-28 10:30',
  },
  {
    id: 2,
    product: 'Mechanical Keyboard',
    quantity: 10,
    price: 75.0,
    added_by: 'Jane Smith',
    created_at: '2025-10-27 15:45',
  },
];

export const recentExitsList = [
  {
    id: 1,
    product: 'USB-C Cable',
    quantity: 5,
    price: 12.99,
    removed_by: 'Mike Johnson',
    created_at: '2025-10-28 09:15',
  },
  {
    id: 2,
    product: 'Laptop Stand',
    quantity: 3,
    price: 45.99,
    removed_by: 'Sarah Williams',
    created_at: '2025-10-27 14:20',
  },
];

export const usersDataList = [
  {
    id: 1,
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    phone: '+1 (555) 123-4567',
    role: 'Admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    location: 'New York, USA',
    joinDate: 'Jan 15, 2024',
    status: 'active',
    productsAdded: 145,
    lastActive: '2 hours ago',
    badge: 'premium',
    stats: { entries: 145, exits: 89, products: 67 },
  },
  {
    id: 2,
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    phone: '+1 (555) 234-5678',
    role: 'Manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    location: 'San Francisco, USA',
    joinDate: 'Feb 20, 2024',
    status: 'active',
    productsAdded: 98,
    lastActive: '1 day ago',
    badge: 'pro',
    stats: { entries: 98, exits: 54, products: 43 },
  },
  {
    id: 3,
    name: 'Emma Williams',
    email: 'emma.williams@company.com',
    phone: '+1 (555) 345-6789',
    role: 'User',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    location: 'London, UK',
    joinDate: 'Mar 10, 2024',
    status: 'inactive',
    productsAdded: 56,
    lastActive: '1 week ago',
    badge: null,
    stats: { entries: 56, exits: 32, products: 28 },
  },
  {
    id: 4,
    name: 'James Rodriguez',
    email: 'james.rodriguez@company.com',
    phone: '+1 (555) 456-7890',
    role: 'Manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    location: 'Miami, USA',
    joinDate: 'Jan 05, 2024',
    status: 'active',
    productsAdded: 213,
    lastActive: '30 min ago',
    badge: 'premium',
    stats: { entries: 213, exits: 167, products: 89 },
  },
  {
    id: 5,
    name: 'Sophia Martinez',
    email: 'sophia.martinez@company.com',
    phone: '+1 (555) 567-8901',
    role: 'User',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
    location: 'Toronto, Canada',
    joinDate: 'Apr 12, 2024',
    status: 'active',
    productsAdded: 78,
    lastActive: '5 hours ago',
    badge: 'pro',
    stats: { entries: 78, exits: 45, products: 34 },
  },
  {
    id: 6,
    name: 'David Kim',
    email: 'david.kim@company.com',
    phone: '+1 (555) 678-9012',
    role: 'Admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    location: 'Seoul, South Korea',
    joinDate: 'Feb 28, 2024',
    status: 'active',
    productsAdded: 189,
    lastActive: 'Just now',
    badge: 'premium',
    stats: { entries: 189, exits: 123, products: 76 },
  },
];
// Sample data matching your screenshot
export const entriesList = [
  {
    id: 1,
    product: 'Halonix 10W Motion Sensor Led bulb',
    addedBy: 'Apple',
    quantity: '4 Units',
    price: '₹120',
    date: '2025-10-31',
    note: 'new shipment recieved',
  },
  {
    id: 2,
    product: 'Wireless Mouse',
    addedBy: 'Apple',
    quantity: '10 Units',
    price: '₹650',
    date: '2025-10-31',
    note: 'new shipment recieved',
  },
  {
    id: 3,
    product: '5v Adapters',
    addedBy: 'Apple',
    quantity: '2 Units',
    price: '₹350',
    date: '2025-10-31',
    note: 'new stock',
  },
  {
    id: 4,
    product: '5v Adapters',
    addedBy: 'Apple',
    quantity: '2 Units',
    price: '₹350',
    date: '2025-10-31',
    note: 'New shipment received from supplier',
  },
  {
    id: 5,
    product: '3mm RGB Lights',
    addedBy: 'Apple',
    quantity: '20 Units',
    price: '₹5',
    date: '2025-10-30',
    note: 'New shipment received from supplier',
  },
  {
    id: 6,
    product: '3mm RGB Lights',
    addedBy: 'Apple',
    quantity: '10 Units',
    price: '₹0',
    date: '2025-10-30',
    note: 'New shipment received from supplier',
  },
  {
    id: 7,
    product: '3mm RGB Lights',
    addedBy: 'Apple',
    quantity: '400 Units',
    price: '₹0',
    date: '2025-10-30',
    note: 'New shipment received from supplier',
  },
];
